name: Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        run: |
          CHROME_VERSION="116.0.5845.225"
          apt-get install -y google-chrome-stable=${CHROME_VERSION}
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"

