name: Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        run: |
          google-chrome --version
          sudo apt-get install -y wget unzip
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6028.0/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo ln -s $PWD/chrome-linux64/chrome /usr/bin/google-chrome
          google-chrome --version
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"

