name: Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 116.0.5845.187
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"

