name: Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=116.0.5845.187-1
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"

