name: Tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        run: |
          VERSION_STRING="116.0.5845.225"
          wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION_STRING}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"

