name: Tests
on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
      branches:
        - master
        - 'release-*'
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "Installed chrome version ..."
          google-chrome --version
      - name: Two
        run: |
          echo "Hi"
          
